name: python-build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.12", "3.14"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: ${{ matrix.python-version }}

      - name: Set up dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Find dfrotz binary
        run: |
          ls -la ~/.pyfrotz
          python -m site
          target_folder=$LD_LIBRARY_PATH/python${{ matrix.python-version }}/site-packages/frotz
          echo $target_folder
          mkdir -p $target_folder
          cp ~/.pyfrotz/dfrotz $target_folder
          ls -la $target_folder

      - name: Test
        run: pytest
